name: Create Deployment Environment

on:
  create:
  pull_request:
    types: [opened, reopened]

concurrency:
  group: ${{ github.event.number || github.ref_name }}

jobs:
  setup:
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    name: Setup Deployment Environment
    runs-on: ubuntu-latest

    outputs:
      type: ${{ steps.setup.outputs.type }}

    steps:
      - uses: actions/checkout@v3

      - name: concurrency ${{ github.event.number || github.ref_name }}
        run: echo "concurrency ${{ github.event.number || github.ref_name }}"

      - name: Setup Deployment Environment
        id: setup
        uses: colbylwilliams/deployment-environments@v1

  create:
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    name: Create Deployment Environment (${{ needs.setup.outputs.type }})
    runs-on: ubuntu-latest

    needs: setup
    environment: ${{ needs.setup.outputs.type }}

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Azure CLI login
        run: az login --service-principal --tenant ${{ vars.AZURE_TENANT_ID }} -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Create Deployment Environment
        id: create
        uses: colbylwilliams/deployment-environments@v1
        with:
          action: create
          summary: true

      - name: AZD Install
        run: curl -fsSL https://aka.ms/install-azd.sh | bash

      - name: AZD Login
        run: azd auth login --tenant-id ${{ vars.AZURE_TENANT_ID }} --client-id ${{ secrets.AZURE_CLIENT_ID }} --client-secret ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: AZD Init
        run: |
          azd config set alpha.resourceGroupDeployments on
          azd init --location eastus2 --subscription $ADE_SUBSCRIPTION --environment $ADE_NAME
          azd env set AZURE_RESOURCE_GROUP $ADE_RESOURCE_GROUP

      - name: AZD Provision
        run: |
          azd provision
          azd env get-values

      - name: AZD Deploy
        run: azd deploy --all

      - name: Get Summary
        id: summary
        run: python3 ./.github/scripts/service_summary.py

      - name: Add Link to Pull Request
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: actions/github-script@v6
        with:
          script: |
            const webUrl = '${{ steps.summary.outputs.web }}'
            const apiUrl = '${{ steps.summary.outputs.api }}'
            const portalUrl = '${{ steps.create.outputs.portal-url }}'

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `The source in this Pull Request has been deployed to Azure for review and can be accessed [here](${portalUrl})\n- View the website: ${webUrl}\n- Explore the API: ${apiUrl}`,
            });
